spring:
  application:
    name: spring-data-jpa-mappings
  h2:
    console:
      enabled: true

  datasource:
    generate-unique-name: false
    name: reinertisa
    username:
    password:
    url: jdbc:h2:mem:reinertisa
  jpa:
    show-sql: true
  sql:
    init:
      platform: h2
  jackson:
    deserialization:
      .fail-on-unknown-properties: true

server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
